language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: uDZ1MR4ZbKiXfqxSorTrxj8/sNYI2IWd2TgbrwBiHUc6oHJ6sHdRCsZgjqbkEdXytNhikXBYPyU5GOtkutwRZWYU6I0Az7dfeex0ipo1RqPRxnXEEN3gPBVtJRbElJkCCwCMCcakHuf+JEjTXOW8EjDUrrtqc2C/01C+Objn/iuN9P9yp3488TnnYlI9tmX5HnTwiLbnfmd+lw0oUik5ChRPoYhLt0BF9rb8nFqPvlYxkJd3pQ3F5wkBF/N62C6wAI/zE3gfvB6rJBb7WvI3kD5xiB5L60uwp6RByvV66lskXYYsNOdEFLqVTvNApGJ+I96TQjK9GLv4uXuGTucZnXWtizZ3AAUoTwmirtKIi257bOsvZaSnvAG/Ex8Esdwl9QsrrsKoNBfbFRiMrzTzZoQRNGtbrcaiDPFmnMOF86+XoVCxgViQ4GuikXg0VixwcB8KHvlJ8RfGIGq9cZ66n8HEhtzRXstgRKqQxjs0waQxxvRJDSfvcVC6DGR6wKluptx/gOVUjnPT6+VBtqkEctYYay3EY2ku51UNo0O/TMNbmqXHpK0Wq/NwiXD07HId5UU0aghgnXVBr4hXpEwE42MvZ7noJfDk8hU9z+LIURb3Ud8oPKfUV+4khE2ECSCMcvvKMP2JhVl0CX5svt6ZW3lSBKck7Q0zQxyAq4sU7Gg=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: jsM2QUFOzVXekuPAXnYFvcHs/tzJQsBuUOuYP9c0m0VJOM1gxWVFjTMPuQ9rnbRvuXif2HJ8MXVBs7OZ6PGRPqC3AGZB53TO6WAEZsZBmrVAw0vsIGocHAYNqt7IcL1YIS75JYB8NlkQoSJAeDJ7gyz0JwkKsSGsdxXW+xritgqG6PrD+bL9FH+M5gkRk0upQw5NDrx3ewz1FKHgdM2Bw6zGmrcU5yxhlJf6kLV1OQjhxKb5Its9XSyxvGCNS7C5jEnR6ihiCSPPQc1Ip8hXS5beuwFJq9Q96rV74q4kJjAFUxZBveZQMGmAAmXiFzwDeg09GEWLlr6altEiTR5oyvi1O63dQ0eX4kxic7yLekrhVg5W7cBze4yGnDXb/A3oJlktuC+3leIhFWhZsWE8NPNcEKObqsIqjVGqpikL3PQK1jYdNleMSeoasAs5zGrtg/Kd9vssHhqD93Vpq+pM7BnYR0w7r0WYJ48vEPIuAOGK71R8a6BHlDy6tjtn3LS3DtApPpbK1kX/eXUArArje17rPDYmJXsO8jwBJuOUSEvyEub3HKCXd2G0e87HydHdt94spfzd2NkMgKFRDqXMkzDvC/YgLHyxyXvvNCUzZwZbZSlLhF7E+bsQ2DEzM1djzpwdlHWOT/y9JJt2byqA6ZVjtCdfqS5UrZZXlPXxhg4=
      on_success: never
      on_failure: always
      on_pull_requests: false
